import type {
  AliskanlikAltAdim,
  AliskanlikOzelTuru,
  AliskanlikProgramTuru,
  AliskanlikZamanDilimi,
} from "@/types/takip";

export const KIMLIK_KATALOG: { kategori: string; kimlik: string }[] = [
  {
    kategori: "İbadet",
    kimlik: "İnancını hayatının merkezinde tutan biriyim.",
  },
  {
    kategori: "Sağlık ve Beden",
    kimlik: "Bedenine düzenli ve şefkatli biçimde bakan biriyim.",
  },
  {
    kategori: "Dil ve Öğrenme",
    kimlik: "Her gün öğrenen ve dillerle yaşayan biriyim.",
  },
  {
    kategori: "Üretim ve Sanat",
    kimlik: "Düzenli üreten ve sanatla bağını koruyan biriyim.",
  },
  {
    kategori: "Kişisel Bakım",
    kimlik: "Kendine özen gösteren biriyim.",
  },
  {
    kategori: "Dijital Denge",
    kimlik: "Dikkatini bilinçli kullanan biriyim.",
  },
];

export const SOSYAL_ALTERNATIFLER = [
  "3 dakika piyano",
  "2 sayfa kitap",
  "5 kelime tekrar",
  "kısa yürüyüş",
  "tek cümlelik içerik fikri",
] as const;

export type PlanSablon = {
  plan_kodu: string;
  ad: string;
  aciklama: string;
  kategori: string;
  kimlik_ifadesi: string;
  program_turu: AliskanlikProgramTuru;
  hedef_gunler: number[];
  hedef_siklik: number | null;
  birim: string | null;
  minimum_deger: number | null;
  hedef_deger: number | null;
  tetikleyici: string | null;
  zaman_dilimi: AliskanlikZamanDilimi;
  sira: number;
  renk: string;
  ikon: string | null;
  ozel_tur: AliskanlikOzelTuru | null;
  asama: number;
  alt_adimlar: AliskanlikAltAdim[];
  karsilayan_plan_kodu?: string;
};

const IBADDET = KIMLIK_KATALOG[0];
const SAGLIK = KIMLIK_KATALOG[1];
const DIL = KIMLIK_KATALOG[2];
const SANAT = KIMLIK_KATALOG[3];
const BAKIM = KIMLIK_KATALOG[4];
const DIJITAL = KIMLIK_KATALOG[5];

export const HAZIR_PLAN: PlanSablon[] = [
  {
    plan_kodu: "namaz",
    ad: "Beş vakit namaz",
    aciklama: "Her vakit ayrı; zinciri tek kutuya indirme.",
    kategori: IBADDET.kategori,
    kimlik_ifadesi: IBADDET.kimlik,
    program_turu: "gunluk",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: "vakit",
    minimum_deger: 1,
    hedef_deger: 5,
    tetikleyici: "Ezan / vakit girince",
    zaman_dilimi: "gun_boyu",
    sira: 10,
    renk: "#b8934a",
    ikon: "Moon",
    ozel_tur: "namaz",
    asama: 1,
    alt_adimlar: [
      { kod: "sabah", ad: "Sabah", grup: "vakit" },
      { kod: "ogle", ad: "Öğle", grup: "vakit" },
      { kod: "ikindi", ad: "İkindi", grup: "vakit" },
      { kod: "aksam", ad: "Akşam", grup: "vakit" },
      { kod: "yatsi", ad: "Yatsı", grup: "vakit" },
    ],
  },
  {
    plan_kodu: "kuran",
    ad: "Kur’an okuma",
    aciklama: "Minimum 4, hedef 20 sayfa.",
    kategori: IBADDET.kategori,
    kimlik_ifadesi: IBADDET.kimlik,
    program_turu: "gunluk",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: "sayfa",
    minimum_deger: 4,
    hedef_deger: 20,
    tetikleyici: "Her namazdan sonra 4 sayfa",
    zaman_dilimi: "gun_boyu",
    sira: 20,
    renk: "#b8934a",
    ikon: "BookOpen",
    ozel_tur: null,
    asama: 1,
    alt_adimlar: [],
  },
  {
    plan_kodu: "beslenme",
    ad: "Düzenli beslenme",
    aciklama: "Ana öğünleri koru; ara öğünler destek.",
    kategori: SAGLIK.kategori,
    kimlik_ifadesi: SAGLIK.kimlik,
    program_turu: "gunluk",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: "öğün",
    minimum_deger: 2,
    hedef_deger: 3,
    tetikleyici: "Mutfağa geçince",
    zaman_dilimi: "gun_boyu",
    sira: 30,
    renk: "#b8934a",
    ikon: "Utensils",
    ozel_tur: "ogun",
    asama: 1,
    alt_adimlar: [
      { kod: "kahvalti", ad: "Kahvaltı", grup: "ana_ogun" },
      { kod: "ogle", ad: "Öğle yemeği", grup: "ana_ogun" },
      { kod: "aksam", ad: "Akşam yemeği", grup: "ana_ogun" },
      { kod: "ara1", ad: "Ara öğün 1", grup: "ara_ogun" },
      { kod: "ara2", ad: "Ara öğün 2", grup: "ara_ogun" },
    ],
  },
  {
    plan_kodu: "sosyal_medya",
    ad: "Sosyal medya farkındalığı",
    aciklama: "Engel değil; niyeti fark et.",
    kategori: DIJITAL.kategori,
    kimlik_ifadesi: DIJITAL.kimlik,
    program_turu: "gunluk",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: null,
    minimum_deger: null,
    hedef_deger: null,
    tetikleyici: "Açmadan önce bir nefes",
    zaman_dilimi: "gun_boyu",
    sira: 40,
    renk: "#6b6158",
    ikon: "Smartphone",
    ozel_tur: "sosyal",
    asama: 1,
    alt_adimlar: [
      { kod: "is", ad: "İş için", grup: "niyet" },
      { kod: "paylasim", ad: "Paylaşım", grup: "niyet" },
      { kod: "mesaj", ad: "Mesajlar", grup: "niyet" },
      { kod: "eglence", ad: "Eğlence", grup: "niyet" },
      { kod: "can_sikintisi", ad: "Can sıkıntısı", grup: "niyet" },
    ],
  },
  {
    plan_kodu: "kendime_vakit",
    ad: "Kendime vakit",
    aciklama: "Üretkenlik görevi değil; durmak.",
    kategori: DIJITAL.kategori,
    kimlik_ifadesi: DIJITAL.kimlik,
    program_turu: "gunluk",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: "dk",
    minimum_deger: 10,
    hedef_deger: 30,
    tetikleyici: "Akşam ekranı kapayınca",
    zaman_dilimi: "aksam",
    sira: 45,
    renk: "#6b6158",
    ikon: "Leaf",
    ozel_tur: null,
    asama: 1,
    alt_adimlar: [],
  },
  {
    plan_kodu: "hareket",
    ad: "Hareket / esneme",
    aciklama: "Spor gününde salonu karşılayabilir.",
    kategori: SAGLIK.kategori,
    kimlik_ifadesi: SAGLIK.kimlik,
    program_turu: "gunluk",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: "dk",
    minimum_deger: 5,
    hedef_deger: 20,
    tetikleyici: "Ayakkabıları giyince",
    zaman_dilimi: "gunduz",
    sira: 50,
    renk: "#b8934a",
    ikon: "StretchHorizontal",
    ozel_tur: null,
    asama: 2,
    alt_adimlar: [],
    karsilayan_plan_kodu: "spor",
  },
  {
    plan_kodu: "spor",
    ad: "Spor salonu",
    aciklama: "İki günde bir. Ev hareketinin yerine geçebilir.",
    kategori: SAGLIK.kategori,
    kimlik_ifadesi: SAGLIK.kimlik,
    program_turu: "iki_gunde_bir",
    hedef_gunler: [],
    hedef_siklik: 3,
    birim: "seans",
    minimum_deger: 1,
    hedef_deger: 1,
    tetikleyici: "Spor çantası kapıda",
    zaman_dilimi: "gunduz",
    sira: 60,
    renk: "#b8934a",
    ikon: "Dumbbell",
    ozel_tur: null,
    asama: 2,
    alt_adimlar: [],
  },
  {
    plan_kodu: "sabah_cilt",
    ad: "Sabah cilt bakımı",
    aciklama: "Minimum: temizlik + nem.",
    kategori: BAKIM.kategori,
    kimlik_ifadesi: BAKIM.kimlik,
    program_turu: "gunluk",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: null,
    minimum_deger: 1,
    hedef_deger: 1,
    tetikleyici: "Yüzü yıkayınca",
    zaman_dilimi: "sabah",
    sira: 70,
    renk: "#b8934a",
    ikon: "Sun",
    ozel_tur: null,
    asama: 2,
    alt_adimlar: [],
  },
  {
    plan_kodu: "aksam_cilt",
    ad: "Akşam cilt bakımı",
    aciklama: "Minimum: temizlik + nem.",
    kategori: BAKIM.kategori,
    kimlik_ifadesi: BAKIM.kimlik,
    program_turu: "gunluk",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: null,
    minimum_deger: 1,
    hedef_deger: 1,
    tetikleyici: "Diş fırçalayınca",
    zaman_dilimi: "aksam",
    sira: 80,
    renk: "#b8934a",
    ikon: "MoonStar",
    ozel_tur: null,
    asama: 2,
    alt_adimlar: [],
  },
  {
    plan_kodu: "uyku",
    ad: "Gece hazırlığı",
    aciklama: "Erken uyanma, önceki gecenin sistemidir.",
    kategori: SAGLIK.kategori,
    kimlik_ifadesi: SAGLIK.kimlik,
    program_turu: "gunluk",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: null,
    minimum_deger: 1,
    hedef_deger: 1,
    tetikleyici: "Hazırlık alarmı",
    zaman_dilimi: "aksam",
    sira: 85,
    renk: "#6b6158",
    ikon: "BedDouble",
    ozel_tur: "uyku",
    asama: 2,
    alt_adimlar: [
      { kod: "hazirlik", ad: "Hazırlık alarmı", grup: "gece" },
      { kod: "telefon", ad: "Telefon yataktan uzak", grup: "gece" },
      { kod: "kalkis", ad: "Alarmdan sonra ayağa kalkma", grup: "sabah" },
    ],
  },
  {
    plan_kodu: "ingilizce",
    ad: "İngilizce",
    aciklama: "Dönüşümlü ana dil; diğer günler mikro tekrar.",
    kategori: DIL.kategori,
    kimlik_ifadesi: DIL.kimlik,
    program_turu: "gunluk",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: "dk",
    minimum_deger: 5,
    hedef_deger: 25,
    tetikleyici: "Masaya oturunca",
    zaman_dilimi: "gunduz",
    sira: 90,
    renk: "#b8934a",
    ikon: "Languages",
    ozel_tur: "dil",
    asama: 3,
    alt_adimlar: [],
  },
  {
    plan_kodu: "fransizca",
    ad: "Fransızca",
    aciklama: "Dönüşümlü ana dil; diğer günler mikro tekrar.",
    kategori: DIL.kategori,
    kimlik_ifadesi: DIL.kimlik,
    program_turu: "gunluk",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: "dk",
    minimum_deger: 5,
    hedef_deger: 25,
    tetikleyici: "Kulaklık takınca",
    zaman_dilimi: "gunduz",
    sira: 100,
    renk: "#b8934a",
    ikon: "Languages",
    ozel_tur: "dil",
    asama: 3,
    alt_adimlar: [],
  },
  {
    plan_kodu: "almanca",
    ad: "Almanca",
    aciklama: "Dönüşümlü ana dil; diğer günler mikro tekrar.",
    kategori: DIL.kategori,
    kimlik_ifadesi: DIL.kimlik,
    program_turu: "gunluk",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: "dk",
    minimum_deger: 5,
    hedef_deger: 25,
    tetikleyici: "Defteri açınca",
    zaman_dilimi: "gunduz",
    sira: 110,
    renk: "#b8934a",
    ikon: "Languages",
    ozel_tur: "dil",
    asama: 3,
    alt_adimlar: [],
  },
  {
    plan_kodu: "yolculuk",
    ad: "Yolculuk",
    aciklama: "Zorunlu üretkenlik yok; seçenek duruyor.",
    kategori: DIL.kategori,
    kimlik_ifadesi: DIL.kimlik,
    program_turu: "esnek",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: null,
    minimum_deger: null,
    hedef_deger: null,
    tetikleyici: "Yola çıkınca",
    zaman_dilimi: "yolculuk",
    sira: 120,
    renk: "#6b6158",
    ikon: "TrainFront",
    ozel_tur: "yolculuk",
    asama: 3,
    alt_adimlar: [
      { kod: "dil_dinleme", ad: "Dil dinleme", grup: "secim" },
      { kod: "kelime", ad: "Kelime tekrarı", grup: "secim" },
      { kod: "kuran_dinleme", ad: "Kur’an dinleme", grup: "secim" },
      { kod: "serbest", ad: "Serbest / sessiz", grup: "secim" },
    ],
  },
  {
    plan_kodu: "piyano",
    ad: "Piyano",
    aciklama: "Haftada 5 gün. Minimum 3 dakika.",
    kategori: SANAT.kategori,
    kimlik_ifadesi: SANAT.kimlik,
    program_turu: "belirli_gunler",
    hedef_gunler: [1, 2, 3, 4, 5],
    hedef_siklik: 5,
    birim: "dk",
    minimum_deger: 3,
    hedef_deger: 15,
    tetikleyici: "Kapağı açınca",
    zaman_dilimi: "aksam",
    sira: 130,
    renk: "#b8934a",
    ikon: "Piano",
    ozel_tur: null,
    asama: 3,
    alt_adimlar: [],
  },
  {
    plan_kodu: "plaktaki_kitap",
    ad: "Plaktaki Kitap üretim hattı",
    aciklama: "Paylaşım iki günde bir; adımlar sırayla.",
    kategori: SANAT.kategori,
    kimlik_ifadesi: SANAT.kimlik,
    program_turu: "iki_gunde_bir",
    hedef_gunler: [],
    hedef_siklik: null,
    birim: "adım",
    minimum_deger: 1,
    hedef_deger: 1,
    tetikleyici: "Masaya oturunca sıradaki adım",
    zaman_dilimi: "gunduz",
    sira: 140,
    renk: "#b8934a",
    ikon: "Clapperboard",
    ozel_tur: "icerik_hatti",
    asama: 4,
    alt_adimlar: [
      { kod: "fikir", ad: "Fikir", grup: "hat" },
      { kod: "arastirma", ad: "Araştırma", grup: "hat" },
      { kod: "metin", ad: "Metin", grup: "hat" },
      { kod: "seslendirme", ad: "Seslendirme", grup: "hat" },
      { kod: "kurgu", ad: "Kurgu", grup: "hat" },
      { kod: "paylasim", ad: "Paylaşım", grup: "hat" },
      { kod: "sonuc", ad: "Sonuç notu", grup: "hat" },
    ],
  },
  {
    plan_kodu: "resim",
    ad: "Resim",
    aciklama: "Haftada 1–2. Minimum malzemeyi hazırlamak.",
    kategori: SANAT.kategori,
    kimlik_ifadesi: SANAT.kimlik,
    program_turu: "haftada_x",
    hedef_gunler: [],
    hedef_siklik: 2,
    birim: "dk",
    minimum_deger: 5,
    hedef_deger: 45,
    tetikleyici: "Boş ve uygun bir öğleden sonra",
    zaman_dilimi: "gunduz",
    sira: 150,
    renk: "#b8934a",
    ikon: "Palette",
    ozel_tur: null,
    asama: 4,
    alt_adimlar: [],
  },
  {
    plan_kodu: "sac",
    ad: "Saç bakımı",
    aciklama: "Başlangıçta haftada 2.",
    kategori: BAKIM.kategori,
    kimlik_ifadesi: BAKIM.kimlik,
    program_turu: "haftada_x",
    hedef_gunler: [],
    hedef_siklik: 2,
    birim: null,
    minimum_deger: 1,
    hedef_deger: 1,
    tetikleyici: "Duştan önce",
    zaman_dilimi: "aksam",
    sira: 160,
    renk: "#6b6158",
    ikon: "Sparkles",
    ozel_tur: null,
    asama: 4,
    alt_adimlar: [],
  },
];

export const ASAMA_ETIKET = [
  "1. hafta — namaz, Kur’an, öğünler, dijital denge",
  "2. hafta — hareket, spor, bakım, gece hazırlığı",
  "3. hafta — diller, yolculuk, piyano",
  "4. hafta — Plaktaki Kitap, resim, saç bakımı",
] as const;

export function anaDilPlanKodu(
  weekday: number
): "fransizca" | "ingilizce" | "almanca" | "tekrar" {
  if (weekday === 1 || weekday === 4) return "fransizca";
  if (weekday === 2 || weekday === 5) return "ingilizce";
  if (weekday === 3 || weekday === 6) return "almanca";
  return "tekrar";
}

export function previewHazirPlan(
  existing: { plan_kodu: string | null }[],
  maxAsama: number
): { eklenecek: PlanSablon[]; atlanan: PlanSablon[] } {
  const have = new Set(
    existing.map((h) => h.plan_kodu).filter((k): k is string => Boolean(k))
  );
  const eklenecek: PlanSablon[] = [];
  const atlanan: PlanSablon[] = [];
  for (const s of HAZIR_PLAN) {
    if (s.asama > maxAsama) continue;
    if (have.has(s.plan_kodu)) atlanan.push(s);
    else eklenecek.push(s);
  }
  return { eklenecek, atlanan };
}
